# Generated by Django 4.2.30 on 2026-08-13 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essaysubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Awaiting review'), ('in_review', 'In review'), ('reviewed', 'Reviewed')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text="Teacher's written assessment", null=True),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='teacher_score',
            field=models.IntegerField(blank=True, help_text='Teacher-assigned score out of 100', null=True),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback', null=True),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='score',
            field=models.IntegerField(default=0, help_text='AI-generated score out of 100'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.essaysubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
